name: VeganSurvival
main: com.Jongyeol.vegan.Main
version: 1.5.0
api-version: 1.13
commands:
  vegan:
    description: 비건 수치를 수정합니다.
    usage: /vegan <set/show/add/remove/give/config>
    permission: vegan.command