name: VeganSurvival
main: com.Jongyeol.vegan.Main
version: 1.2.1
api-version: 1.13
commands:
  vegan:
    description: 비건 수치를 수정합니다.
    usage: /vegan <set/show/add/remove/give> <player> <vegan/item>
    permission: vegan.command